### ISSUE TITLE
publish 1.3.1

### ISSUE THREAD

**Issue by douardda** [typeddjango/djangorestframework-stubs#111]
Could it be possible to publish a 1.3.1 version that includes the last 2 revisions?

thanks,
David

**Comment by WisdomPill** [comment]
+1

**Comment by Goldziher** [comment]
yes, we should be able to get a release @sobolevn 

what is teh changelog?

**Comment by intgr** [comment]
Yes please, lots of good stuff has been merged since the last release.

Though it won't be a minor release any more, more like 1.4.0

**Comment by sobolevn** [comment]
Done! https://github.com/typeddjango/djangorestframework-stubs/releases/tag/1.4.0

**Comment by sobolevn** [comment]
And https://pypi.org/project/djangorestframework-stubs/1.4.0/
