### ISSUE TITLE
generics.ViewSet.get_serializer_class incorrect typing 

### ISSUE THREAD

**Issue by Eugeny** [typeddjango/djangorestframework-stubs#116]
`generics.ViewSet.get_serializer_class()` returns `Type[BaseSerializer[_MT_co]]`, but is typed as `BaseSerializer[_MT_co]` in drf-stubs

**Comment by sobolevn** [comment]
@Eugeny PRs are welcome!

**Comment by Eugeny** [comment]
My bad, it's already been fixed in #110. Any chance to cut a release soon?

**Comment by sobolevn** [comment]
Yes, I will do it soon. I am very busy this half-a-year 😞
