### ISSUE TITLE
Support serializer field with name "fields"

### ISSUE THREAD

**Issue by kalekseev** [typeddjango/djangorestframework-stubs#12]
Consider the case:

```python
 class FieldsSerializer(serializers.Serializer):
     ...
 
 
 class OtherSerializer(serializers.Serializer):
    fields = FieldsSerializer()
```

Mypy will complain with: `error: Incompatible types in assignment (expression has type "FieldsSerializer", base class "Serializer" defined the type as "Dict[str, Field]")`

**Comment by MarcinWieczorek** [comment]
You're trying to shadow Serializer's property `fields`, I think you really shouldn't do that, internals might be relying on that

**Comment by MarcinWieczorek** [comment]
imho it's a wontfix and should be closed.

**Comment by sobolevn** [comment]
I agree. `fields` is defined in `Serializer`. The best practice is not to override names like that.
