### ISSUE TITLE
status.HTTP_200_OK is Literal[202]

### ISSUE THREAD

**Issue by vhtkrk** [typeddjango/djangorestframework-stubs#123]
`rest_framework-stubs/status.pyi` defines HTTP_200_OK as follows:

    HTTP_200_OK: Literal[202] 

I believe this should be `Literal[200]`. DRF's `rest_framework/status.py` agrees:

    HTTP_200_OK = 200

**Comment by sobolevn** [comment]
@vhtkrk PR is welcome!
