### ISSUE TITLE
ModelSerializer.Meta.model should be a Type[_MT] not _MT

### ISSUE THREAD

**Issue by palfrey** [typeddjango/djangorestframework-stubs#126]
As it's not a model instance, but a type. Similar also to BaseManager.model in https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/manager.pyi#L14

**Comment by sobolevn** [comment]
@palfrey thanks for the report! PRs are welcome!

**Comment by palfrey** [comment]
> @palfrey thanks for the report! PRs are welcome!

See https://github.com/typeddjango/djangorestframework-stubs/pull/127
