### ISSUE TITLE
metadata_class should allow classes that inherit BaseMetadata

### ISSUE THREAD

**Issue by Hanicef** [typeddjango/djangorestframework-stubs#134]
The `metadata_class` field in `APIView` allows classes that inherit `BaseMetadata` to be used; however, the stub currently only allows `None` and `str`: https://github.com/typeddjango/djangorestframework-stubs/blob/f74916e46ed86f221492becded4b83bceb0ff1a0/rest_framework-stubs/views.pyi#L42

The documentation about this is here: https://www.django-rest-framework.org/api-guide/metadata/#setting-the-metadata-scheme

**Comment by sobolevn** [comment]
@Hanicef PRs are welcome! 👍
