### ISSUE TITLE
Why `ModelSerializer.instance` is `Option[Union[_MT, Sequence[_MT]]]` and not `Option[_MT]`?

### ISSUE THREAD

**Issue by linevych** [typeddjango/djangorestframework-stubs#136]
I can't quite understand in what case `ModelSerializer.instance` could be `Sequence[_MT]`.

**Comment by oystein-beaufort** [comment]
I believe that happens when `many=True`

**Comment by intgr** [comment]
FWIW this behavior has been changed in version `3.16.3` in https://github.com/typeddjango/djangorestframework-stubs/pull/719
