### ISSUE TITLE
Incompatible type for lookup "user"

### ISSUE THREAD

**Issue by nico-deforge** [typeddjango/djangorestframework-stubs#147]
# Bug report

Hello everyone, thank you for this awesome project.

I have a mypy error that I can not resolve : 

Incompatible type for lookup 'user': (got "Union[User, AnonymousUser]", expected "Union[User, UUID, None, None]")mypy(error)

## What's wrong

Here is my code : 

`class StudentViewSet(
    mixins.RetrieveModelMixin,
    mixins.ListModelMixin,
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    serializer_class = StudentSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self) -> QuerySet[Student]:
        if self.request.method in SAFE_METHODS:
            return Student.objects.all()
        else:
            return Student.objects.filter(user=self.request.user)`

The error is on the user lookup in the second queryset.

Can you help me to resolve this ?

## How is that should be

No error on the line

## System information

- OS:
- `python` version: 3.8.8
- `django` version: 3.2
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0
- `djangorestframework-stubs` version: 1.4.0

Thank you !

**Comment by sobolevn** [comment]
This happens because:

> Incompatible type for lookup 'user': (got "Union[User, AnonymousUser]", expected "Union[User, UUID, None, None]")

And you cannot have `AnonymousUser` in your `user=` query. 
I would recommend to use `assert isinstance(self.request.user, User)` right before the query.

Or, you can use https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user

**Comment by nico-deforge** [comment]
Thank you very much.

I did this and it is working well.

`def get_queryset(self) -> QuerySet[Student]:
        if self.request.method not in SAFE_METHODS and isinstance(
            self.request.user, User
        ):
            return Student.objects.filter(user=self.request.user)
        else:
            return Student.objects.all()`

In fact mypy forces us to be more rigorous on the context.

I close the issue
