### ISSUE TITLE
Missing type parameters for generic type “ModelSerializer”

### ISSUE THREAD

**Issue by sant527** [typeddjango/djangorestframework-stubs#164]
# Bug report

I have 

```
class AnimalSerializer(serializers.ModelSerializer):
    class Meta:
        model = Animal
        fields = "__all__"
```

Now i run mypy 

```
[mypy]
# The mypy configurations: https://mypy.readthedocs.io/en/latest/config_file.html
python_version = 3.9

check_untyped_defs = True
# disallow_any_explicit = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
ignore_errors = False
ignore_missing_imports = True
implicit_reexport = False
strict_optional = True
strict_equality = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = True
warn_no_return = True
mypy_path = /home/simha/app/backend_django/src

plugins =
  mypy_django_plugin.main,
  mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = petsproject.settings
```
```
(venv) $ mypy .
```

I get 

```
error: Missing type parameters for generic type "ModelSerializer"

```

## System information

- OS:
- `python` 3.9:
- `django` 3.1:
- `mypy` 0.910
- `django-stubs` 1.8.0
- `djangorestframework-stubs` 1.4.0

**Comment by sobolevn** [comment]
This is how `ModelSerializer` is defined: https://github.com/typeddjango/djangorestframework-stubs/blob/master/rest_framework-stubs/serializers.pyi#L214

You can:
1. Define your subtype as `class AnimalSerializer(serializers.ModelSerializer[Animal]):`
2. Disable these errors with `disallow_any_generics = False`

I hope this helps!

**Comment by browniebroke** [comment]
> 1. Define your subtype as `class AnimalSerializer(serializers.ModelSerializer[Animal]):`

I didn't realise that was supported until stumbling upon this issue, this is amazing! Did I miss the documentation or it doesn't exist? I noticed that the `django-stubs` project has a "Features" section showing these kind of things, would it make sense to create one on this project too? I'm happy to send a PR
