### ISSUE TITLE
Altering serializer_field_mapping

### ISSUE THREAD

**Issue by aleehedl** [typeddjango/djangorestframework-stubs#166]
# Bug report

## What's wrong

I'm trying to add custom serializer_field_mapping to my serializer.

```
from django.db import models
from rest_framework.serializers import ModelSerializer as DRFModelSerializer
from rest_framework.fields import DateTimeField as DRFDateTimeField

class MyDateTimeField(DRFDateTimeField):
    # do something custom
    pass


class ModelSerializer(DRFModelSerializer):
    serializer_field_mapping = {
        **DRFModelSerializer.serializer_field_mapping,
        models.DateTimeField: MyDateTimeField,
    }

```

Running mypy gives me these errors:
```
error: Argument 1 to "update" of "dict" has incompatible type 
"Dict[Type[django.db.models.fields.Field[Any, Any]], rest_framework.fields.Field[Any, Any, Any, Any]]"; 
expected "Mapping[Type[django.db.models.fields.DateTimeField[Any, Any]], Type[my_lorien.api.fields.DateTimeField]]"

error: Dict entry 0 has incompatible type "Type[DateTimeField[Any, Any]]": "Type[DateTimeField]"; 
expected "Type[Field[Any, Any]]": "Field[Any, Any, Any, Any]"
```
## How is that should be

No errors

## System information

- OS:
- `python` version: 3.9.2
- `django` version: 3.1.13
- `mypy` version: 0.910
- `django-stubs` version: 1.9.0

How should I go about this?

**Comment by sobolevn** [comment]
Ok, looks like this is a `Dict` invariance issue. Do you want to solve this? 🙂

**Comment by aleehedl** [comment]
I'm afraid I'm not yet fluent enough with type hints to solve this :)

**Comment by aleehedl** [comment]
Seems to me that this has been fixed but not released yet:
https://github.com/typeddjango/djangorestframework-stubs/commit/27533ac5adb937588f402f333df6afc17f3343dd

**Comment by sobolevn** [comment]
ETA somewhere in semptember.

I am going to close this, since it was fixed. Thanks a lot!
