### ISSUE TITLE
Extending serializer Meta class results in type mismatch

### ISSUE THREAD

**Issue by greg-finley-bond** [typeddjango/djangorestframework-stubs#169]
## What's wrong

```
from rest_framework import serializers

from credit.models import Application

class BaseApplicationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Application
        fields = None
        exclude = ["ssn"]
        abstract = True


class GetAllApplicationSerializer(BaseApplicationSerializer):
    class Meta(BaseApplicationSerializer.Meta):
        fields = "__all__"
        exclude = None
```

It doesn't like that I'm making `fields` be `__all__` when it was `None` in the parent and making `exclude` be `None` when it was a `List[str]` in the parent.
```
credit/serializers.py:16: error: Incompatible types in assignment (expression has type "str", base class "Meta" defined the type as "None")
credit/serializers.py:17: error: Incompatible types in assignment (expression has type "None", base class "Meta" defined the type as "List[str]")
```

## How is that should be
It's probably a user error on my side. It would be great to leverage the types you have here:
https://github.com/typeddjango/djangorestframework-stubs/blob/7f698898dd6b230b146559dc45643d7c2a2ba329/rest_framework-stubs/serializers.pyi#L222-L228

## System information

- OS: macOS
- `python` version: 3.9
- `django` version: "^3.2.8"
- `mypy` version: "^0.910"
- `django-stubs` version: "^1.9.0"

**Comment by sobolevn** [comment]
> It's probably a user error on my side

It looks like it is! Please, let me explain: when you extend your own `Meta` model, you change the typing rules.

```python
class Meta(BaseApplicationSerializer.Meta):
        fields = "__all__"
        exclude = None
```

What you say here is:
- override parent's `field` attribute that has `None` type with `str` type
- override parent's `exclude` attribute that has `List[str]` type with `None`

Try this instead:

```python
class BaseApplicationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Application
        exclude: Optional[Sequence[str]] = ["ssn"]
        abstract = True
```

**Comment by greg-finley-bond** [comment]
Awesome! This will work for me. Thanks for your help and your explanation.
