### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by intgr** [typeddjango/djangorestframework-stubs#193]
I'd like to be able to use #152 in my application, which was merged last June. There are also plenty of other useful improvements merged.

Thanks for continued maintenance of this project.

**Comment by pmazspoton** [comment]
Please release the version that @stianjensen mentioned : "Add django-stubs v1.10.0 compatibility (#203)" :)

**Comment by sobolevn** [comment]
Releasing `1.5.0` 🎉
