### ISSUE TITLE
"HttpResponse" has no attribute "data"

### ISSUE THREAD

**Issue by XF-FW** [typeddjango/djangorestframework-stubs#204]
# Bug report

## What's wrong

When running `mypy` with the `--strict` flag on a test it will raise `error: "HttpResponse" has no attribute "data"`

Test example:
```
# api/tests.py (lines 9-12)
class ExampleTest(APITestCase):
    def test_failure(self) -> None:
        response = self.client.get('/hello/', format="json")
        self.assertEqual(response.data["message"], "Hello, world!")
```

## How is that should be

`mypy` should not complain about `response` not having the `data` attribute.

## How to reproduce

Repo to reproduce the issue:  
https://github.com/XF-FW/issue-drf-stubs-response
Github action that fails when running `mypy` due to the issue in question:  
https://github.com/XF-FW/issue-drf-stubs-response/runs/5759647545?check_suite_focus=true

## Why

- Is django-stubs not in the latest version?
  - #202 

## Have you tried:

- Upgrading django-stubs and not using the drf-stubs mypy plugin?
   - Yes. It does not work.
- Using the `master` branch, instead of the lastest release?
   - Yes. It does not work. Although I expected it to work, since something similar is mentioned in the CHANGELOG. For reference: https://github.com/typeddjango/djangorestframework-stubs/blob/master/CHANGELOG.md?plain=1#L10
- Applying the same changes that #105 did?
   - Yes. **It does work!**

## The end.
Thanks for putting up with me. Let me know if I can help in any way.

**Comment by sobolevn** [comment]
PRs are very much appreciated 😉 
I don't use drf myself, so I don't have any time to keep up with all the changes / problems.

Thanks for the detailed report!

**Comment by XF-FW** [comment]
I totally understand. I'll gladly create a PR.

My first instinct is to repeat the changes on #105. I think I'll do that and then see where the CI leads me.

Thank you!

**Comment by YPCrumble** [comment]
@XF-FW thanks for this - this is something that has really been bugging me as well! I suspect that it might be related to #129 - do you think your PR also solves that issue? 

Essentially for my code it seems that the `APITestCase` has a client typed as `django.test.client.Client` instead of `APIClient` as you've done here. So I think this does solve the issue above as well.

**Comment by XF-FW** [comment]
Glad to help, @YPCrumble . I think it does. All my TestCase classes are subclassed and using my PR, made all errors go away.

@sobolevn would you be able to aprove the PR's CI workflow? Thank you!
