### ISSUE TITLE
rest_framework.permissions.BasePermission causes a Metaclass conflict error

### ISSUE THREAD

**Issue by mattwwarren** [typeddjango/djangorestframework-stubs#282]
# Bug report

## What's wrong

After upgrading to mypy 0.990 (from 0.982), the following code example causes a Metaclass conflict

```
from rest_framework.permissions import BasePermission

class OrgPermissions(BasePermission):
    ...
```

## How it should be

Running mypy on the above class should not cause
> error: Metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases  [misc]

I'm also willing to accept this is an improper use of Metaclasses by drf directly but I've never seen this error in running code so I figured I would start with a bug here.

## System information

- OS: Linux
- `python` version: 3.9.x
- `django` version: 4.0.x
- `mypy` version: 0.990
- `django-stubs` version: 1.12.x

**Comment by jwhitlock** [comment]
Also seen in PR #280, signature of `BasePermission` changed. Updating to `djangorestframework-stubs` 1.8.0, which includes that change, fixed it for me.

**Comment by dmartin** [comment]
Upgrading to 1.8.0 resolved this error for me as well.

**Comment by mattwwarren** [comment]
Can confirm upgrading to 1.8.0 fixed the original issue. Thank you!
