### ISSUE TITLE
Conflict with Django Stubs

### ISSUE THREAD

**Issue by ThalusA** [typeddjango/djangorestframework-stubs#298]
# Bug report

## What's wrong

```bash
The conflict is caused by:
    django-stubs[compatible-mypy] 1.13.0 depends on mypy>=0.980
    django-stubs[compatible-mypy] 1.13.0 depends on mypy<0.990 and >=0.980; extra == "compatible-mypy"
    djangorestframework-stubs[compatible-mypy] 1.8.0 depends on mypy>=0.980
    djangorestframework-stubs[compatible-mypy] 1.8.0 depends on mypy<0.1000 and >=0.991; extra == "compatible-mypy"
```

## How is that should be

`djangorestframework-stubs[compatible-mypy] 1.8.0 depends on mypy<0.1000 and >=0.991; extra == "compatible-mypy"`
Why having so much restriction about mypy package version when there is no major changes ?  
It should at least match:
 `django-stubs[compatible-mypy] 1.13.0 depends on mypy<0.990 and >=0.980; extra == "compatible-mypy"`

## System information

- OS: Linux (Fedora 37)
- `python` version: 3.11
- `django` version: 4.1.3
- `mypy` version: ???
- `django-stubs` version: 1.8.0

**Comment by intgr** [comment]
Yep django-stubs isn't fully compatible with mypy 0.99x yet.

IMO don't use `[compatible-mypy]` with both django-stubs and djangorestframework-stubs at the same time. In my own projects I don't use this feature at all.

@sobolevn Any thoughts here? Or should we just pay attention to keep `[compatible-mypy]` versions in sync between django-stubs and djangorestframework-stubs?

**Comment by sobolevn** [comment]
> Or should we just pay attention to keep [compatible-mypy] versions in sync between django-stubs and djangorestframework-stubs?

Yes, I think so. 

+ poetry should handle this automatically.

**Comment by intgr** [comment]
This conflict was solved with django-stubs 1.14.0 release, which bumps compatible-mypy to 0.991: https://github.com/typeddjango/django-stubs/releases/tag/1.14.0

In the future I'll try to make sure they don't go out of sync again.

**Comment by ThalusA** [comment]
Sadly it got out of sync again :/ @intgr

**Comment by intgr** [comment]
Aaaand djangorestframework-stubs 1.10.0 released too:

* https://pypi.org/project/djangorestframework-stubs/1.10.0/#history
* https://github.com/typeddjango/djangorestframework-stubs/releases/tag/1.10.0

Will edit release notes in a moment.
