### ISSUE TITLE
Typings for Field attributes

### ISSUE THREAD

**Issue by kalekseev** [typeddjango/djangorestframework-stubs#31]
Currently a lot of Field's attributes are not exposed in types, eg:

```
error: "ChoiceField" has no attribute "field_name"
error: "Field" has no attribute "allow_blank"
error: "Field" has no attribute "allow_null"
error: "Field" has no attribute "default"; maybe "get_default"?
error: "Field" has no attribute "read_only"
error: "Field" has no attribute "required"
```

that cause a lot of headache when serializers modified dynamically.

**Comment by stevanmilic** [comment]
@sobolevn I would like to fix this. I'll provide a PR that passes the pipeline.

**Comment by kalekseev** [comment]
@stevanmilic I created a pr but it wasn't merged and after some of the fields were fixed in master it has merge conflict. You can use that pr as starting point.

**Comment by kalekseev** [comment]
@stevanmilic another related non merged pr https://github.com/typeddjango/djangorestframework-stubs/pull/58/files

**Comment by stevanmilic** [comment]
Yea seen it, I was planning to re-use it 👍 thanks

**Comment by stevanmilic** [comment]
@kalekseev I've just taken a look at master branch, it looks like the attributes are added in https://github.com/typeddjango/djangorestframework-stubs/commit/211242535821f7974522a8445b354c31d4e3e10c#diff-279543faf36724e6286925cb91487e5e commit, we can close this issue.

**Comment by sobolevn** [comment]
Yes, I have merged it today. Sorry for the delay!
