### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by mschoettle** [typeddjango/djangorestframework-stubs#324]
Following the release of `django-stubs` (typeddjango/django-stubs#1316) would it be possible to release a new version of these stubs as well?

I am not too familiar with it but it seems that this might be a blocker:

*  [update for StrOrPromise in typeddjango/django-stubs #301](https://github.com/typeddjango/djangorestframework-stubs/pull/301)

Are there any other issues that should be included in the next release?

@sobolevn @intgr

**Comment by intgr** [comment]
Sorry, I missed this issue before. Yes certainly, now with django-stubs 1.14.0 out the door I'll concentrate more on djangorestframework-stubs.

**Comment by mschoettle** [comment]
Thanks! If there is anything I can do to help let me know.

**Comment by intgr** [comment]
* The CI is broken right now on master, this should fix it:
  * #345
* After that, it would be great to merge mypy 1.0 support:
  * #339
* Then would be great to make a release of both django-stubs and djangorestframework-stubs with mypy 1.0 support.

**Comment by intgr** [comment]
Also this should be mergeable now:

*  #284

**Comment by intgr** [comment]
Aaaand it's out! Release notes will be edited soon.

* Release notes: https://github.com/typeddjango/djangorestframework-stubs/releases/tag/1.9.0
* https://pypi.org/project/djangorestframework-stubs/1.9.0/#history

**Comment by intgr** [comment]
Release notes have been edited.
