### ISSUE TITLE
Support for Mypy 0.730

### ISSUE THREAD

**Issue by hannseman** [typeddjango/djangorestframework-stubs#35]
Mypy 0.730 have been released and `setup.py` specifies `mypy>=0.720,<0.730` while django-stubs specifies `mypy>=0.730` in `1.2.0`. See: https://github.com/typeddjango/django-stubs/blob/master/setup.py#L24

**Comment by sobolevn** [comment]
@hannseman thanks a lot for the feature request! Any help is appreciated 🙂

**Comment by Beefy-Swain** [comment]
Any idea when support for mypy 0.740 will happen?

**Comment by sobolevn** [comment]
Done #41
