### ISSUE TITLE
Enable pre-commit.ci on this repo as well?

### ISSUE THREAD

**Issue by intgr** [typeddjango/djangorestframework-stubs#358]
@sobolevn I noticed that the `django-stubs` repository has a pre-commit.ci job that doesn't run in this repo. I tried enabling it myself, but it didn't seem to work.

Can you take a look?

**Comment by sobolevn** [comment]
Sure, I am on it.

**Comment by sobolevn** [comment]
Done!

**Comment by intgr** [comment]
Great, thanks
