### ISSUE TITLE
Version 1.9.0 breaks build with latest django and DRF

### ISSUE THREAD

**Issue by GTorreil** [typeddjango/djangorestframework-stubs#362]
# Bug report

## What's wrong

with the following in requirements.txt :

```
django == 4.1.7
djangorestframework == 3.14.0
djangorestframework-stubs == 1.9.0
```

Running the server fails :

```
  File "/app/api/urls.py", line 4, in <module>
    from rest_framework import routers
  File "/usr/local/lib/python3.11/site-packages/rest_framework/routers.py", line 19, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.11/site-packages/django/conf/urls/__init__.py)
```

But with the following requirements.txt :

```
django == 4.1.7
djangorestframework == 3.14.0
```

followed by `pip install --force-reinstall -r requirements.txt`, the server works

## How is that should be

The server should work.

## System information

- OS: Ubuntu 22.10
- `python` version: 3.10.7
- `django` version: 4.1.7
- `mypy` version: 1.0.1
- `django-stubs` version: 1.9.0

--- 

Sorry for the sparse information, I am in a hurry right now but I wanted to let you know. 

Best,

**Comment by monosans** [comment]
I managed to find the reason. The wheel file in PyPi for some reason contains the sources of Rest Framework 3.11. As a result, when installing stubs, it replaces the installed Rest Framework with its own copy.

**Comment by monosans** [comment]
I think this wheel should be removed from PyPi ASAP, so that people installing it won't break their local Rest Framework installation and wonder why their Rest Framework stopped working.

**Comment by simonkern** [comment]
Dependabot just opened a PR for this version and our test runners show the error described above as well.

**Comment by ms32035** [comment]
I ran into some other import errors with the latest DRF

**Comment by intgr** [comment]
Oh damn. @sobolevn Can you yank/delete the latest djangorestframework-stubs release?

**Comment by intgr** [comment]
Other possible symptoms of this issue:

* TypeError: type 'ModelSerializer' is not subscriptable
* RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.

**Comment by intgr** [comment]
Sorry for the slow response, turns out I wasn't subscribed to new issues in _this_ project.

**Comment by intgr** [comment]
I added this guidance to release notes:

> Emergency release to fix packaging issues in yesterday's version.
>
> For yet unknown reasons, the wheel package of djangorestframework-stubs 1.9.0 also contained the full source code of Django REST Framework version 3.11. Thus installing djangorestframework-stubs 1.9.0 would **overwrite djangorestframework files**.
>
> To fix an installation with this issue: `pip uninstall djangorestframework djangorestframework-stubs && pip install djangorestframework djangorestframework-stubs==1.9.1` (tweak as necessary if you need a particular djangorestframework version)
>
> Thanks to @monosans for debugging this issue. For details, see https://github.com/typeddjango/djangorestframework-stubs/issues/362

**Comment by intgr** [comment]
I checked earlier PyPI releases as well and luckily it seems they were not affected.

I can reproduce this issue too. The `rest_framework` files are only included in the wheel pacakge, not sdist, as can be seen from the file sizes:

```
-rw-r--r--  1     32K Feb 23 15:07 djangorestframework-stubs-1.9.0.tar.gz
-rw-r--r--  1    207K Feb 23 15:07 djangorestframework_stubs-1.9.0-py3-none-any.whl
```

Apparently at some point I had placed DRF source to `./rest_framework` in my git checkout and invoked the build scripts, which had copied it into `./build/lib/rest_framework`. If I abort the `release.sh` script at the point where it asks for my PyPI password, the build and dist directories are not deleted.

When building 1.9.0 release the `./rest_framework` directory was no longer present, but it still remained in `./build/lib/rest_framework` from the last build.

In `release.sh`, the clean command `rm -rf dist/ build/` currently only runs _after_ a successful build. I think a good precaution is to run it before building as well.

**Comment by intgr** [comment]
In general I'm not a fan of running package builds from a development environment. Ideally it would be done in some isolated CI environment.

But for now, I think a reasonable solution is to create a separate always clean git checkout for making releases.

**Comment by GTorreil** [comment]
Thanks a lot for reacting this quickly !
