### ISSUE TITLE
Python 3.11, support new http.HTTPMethod enum in action and view

### ISSUE THREAD

**Issue by sshishov** [typeddjango/djangorestframework-stubs#396]
# Bug report

When using python 3.11, instead of hardcoding HTTP verbs, now we can use official enum: `HTTPMethod` as well as `HTTPStatus` for statuses

## What's wrong

We would like to use it in `decorators.action(methods=[HTTPMethod.POST])` for instance.
Currently it does not work and produce the following error:
```python
error: List item 0 has incompatible type "Literal[HTTPMethod.POST]"; expected "Literal['GET', 'POST', 'DELETE', 'PUT', 'PATCH', 'TRACE', 'HEAD', 'OPTIONS', 'get', 'post', 'delete', 'put', 'patch', 'trace', 'head', 'options']"  [list-item]
```

## How is that should be

No `mypy` error should be reported

## System information

- OS: MacOS / Debian (docker)
- `python` version: 3.11
- `django` version: 3.2.18
- `mypy` version: 1.2.0
- `django-stubs` version: 1.16.0
- `djangorestframework-stubs` version: 1.10.0

**Comment by intgr** [comment]
I'm unsure about this.

While `StrEnum`s like `HTTPMethod.POST` _try to behave_ similar to the string `"POST"`, and indeed it's even subclassing `str`, I'm afraid there can be subtle differences in behavior. It could trip some edge case in DRF code and lead to different behavior.

As far as I can tell, there are no unit tests in DRF that use `HTTPMethod`, nor are there any examples in documentation.

I would be comfortable with allowing this when we have some commitment from DRF upstream that this will be supported going forward, preferably in the form of tests or documentation examples.

So maybe open an issue with DRF upstream and see what they think.

**Comment by sshishov** [comment]
Thank you @intgr , going to create the ticket on DRF itself, if they will be willing to support this standard library enums

**Comment by sshishov** [comment]
Hello @intgr ,  the parent issue has been fixed and merged? Can we do something here also to go forward?

**Comment by intgr** [comment]
Yes, are you interested in creating a pull request?

**Comment by sshishov** [comment]
I can try to do it @intgr , will do it in close future. Thanks 👍
