### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lundberg** [typeddjango/djangorestframework-stubs#43]
A version bump and pypi release would be great.

Thanks

...also, a lot of pypi releases is missing as github tags/releases.

**Comment by unmade** [comment]
A new release will be very welcome as for now there is a conflict in dependencies with `django-stubs`

```
There are incompatible versions in the resolved dependencies:
  mypy<0.730,>=0.720 (from djangorestframework-stubs==1.0.0->-r dev-requirements.in (line 2))
  mypy<0.760,>=0.750 (from django-stubs==1.3.0->djangorestframework-stubs==1.0.0->-r dev-requirements.in (line 2))
```

**Comment by brianhelba** [comment]
Indeed. @sobolevn @mkurnikov , could we please get a release to fix comparability with the most recent `django-stubs`?
