### ISSUE TITLE
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by clement-escolano** [typeddjango/djangorestframework-stubs#431]
# Bug report

## What's wrong
When running mypy to check the types of my project, I see this warning:
```
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```

I know this is a dependency of `coreapi` and not a direct dependency of this package but `coreapi` has not been updated for 5 years and the [repository](https://github.com/core-api/python-client) is archived so this probably requires dropping the dependency some day.

## How is that should be

There should not be any warning.

## System information

- OS:
- `python` version: 3.11
- `django` version: 4.2.2
- `mypy` version: 0.942
- `django-stubs` version: 1.10.1

**Comment by intgr** [comment]
If you uninstall `coreapi` from your virtualenv, I believe this error should disappear.

**Comment by clement-escolano** [comment]
Oh perfect then, sorry for the trouble.
Thank you!
