### ISSUE TITLE
Change how we use `DjangoContext` after https://github.com/typeddjango/django-stubs/pull/1557

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/djangorestframework-stubs#432]
The signature of `DjangoContext` is changed in the linked PR (https://github.com/typeddjango/django-stubs/pull/1557), so we would need to change the source code here: https://github.com/typeddjango/djangorestframework-stubs/blob/8709db5d2af980919a46072725ab54ca637a8703/mypy_drf_plugin/main.py#L25-L26

And bump the `django-stubs` minimal version support.

**Comment by intgr** [comment]
Can you create a pull request for djangorestframeworks-stubs too?

To test it you can change `requirements.txt` to point to your django-stubs branch.

**Comment by sobolevn** [comment]
Hm, I think we would need a compat layer: because of how `django-stubs` dep is specified: https://github.com/typeddjango/djangorestframework-stubs/blob/master/setup.py#L24

I will do it right now.
