### ISSUE TITLE
consider `Sequence[Any]` instead of `Iterable[Any]` for `ChoiceField`s `choices`

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/djangorestframework-stubs#454]
this isn't a bug but perhaps a suggestion.

when rest_framework's `ChoiceField` and `MultipleChoiceField` receive an unordered collection for `choices` it can lead to a negative experience: unordered form output, unordered schema, etc.

https://github.com/typeddjango/djangorestframework-stubs/blob/e0e9e1f6ba9411345d00abb904b62c106ca8d7b1/rest_framework-stubs/fields.pyi#L460

we've made a small plugin for `sentry` that enforces this for our uses since we kept hitting this problem:  https://github.com/getsentry/sentry/pull/53707

though this isn't entirely in spirit of the type system so understandable if this isn't a good idea

**Comment by asottile-sentry** [comment]
let me know if you'd like this as a PR: https://github.com/getsentry/sentry-forked-djangorestframework-stubs/commit/989e25abb7fe42073e6757b77f1dbd528664353e

**Comment by sobolevn** [comment]
Looks reasonable! 👍
