### ISSUE TITLE
Bump mypy to 1.5.x

### ISSUE THREAD

**Issue by ippeiukai** [typeddjango/djangorestframework-stubs#462]
Please update compatible-mypy to allow 1.5.x.

related to:
- https://github.com/typeddjango/django-stubs/issues/1651
- https://github.com/typeddjango/djangorestframework-stubs/pull/456

similar to:
- https://github.com/typeddjango/djangorestframework-stubs/pull/437

**Comment by mertcangokgoz** [comment]
yeah, it will be very nice if it is updated for 1.5.x.

**Comment by intgr** [comment]
Fixed in version 3.14.3. Apologies for neglecting this project for so long.
