### ISSUE TITLE
Wrong typing for Exception.detail

### ISSUE THREAD

**Issue by AlwxSin** [typeddjango/djangorestframework-stubs#56]
For now type of `APIException.detail` is `_Detail = Union[str, Dict[str, Any]]`. But it also could be a list.

A possible solution is to set `_Detail = Union[str, List[Any], Dict[str, Any]]`. Would you mind if I make a PR?

**Comment by sobolevn** [comment]
`List[Any]`? Can we narrow this type a bit?

**Comment by AlwxSin** [comment]
I'd like too but don't know how to do it. And there is already `Dict[str, Any]`

**Comment by apragacz** [comment]
@sobolevn Was that change released? It doesn't look like so - the last version (`1.1.0`) was released few weeks earlier... any chance for this change to be released soon?

**Comment by sobolevn** [comment]
Yes, I can make a release this week. Currently you can try `master` branch to see if that works for you. Any issues and bugs are welcome!

**Comment by apragacz** [comment]
@sobolevn Thanks for you answer!

I suppose I will wait for the official release and remove `type: ignore` comments in my code later.
