### ISSUE TITLE
Copy CONTRIBUTING.md from django-stubs

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/djangorestframework-stubs#65]
https://github.com/typeddjango/django-stubs/blob/master/CONTRIBUTING.md

**Comment by jhabarsingh** [comment]
@sobolevn can yau assign this to me ?

**Comment by sobolevn** [comment]
With great pleasure! Thank you!

**Comment by jhabarsingh** [comment]
I have copied it. can I send a PR now .
