### ISSUE TITLE
Please do a new release

### ISSUE THREAD

**Issue by intgr** [typeddjango/djangorestframework-stubs#66]
Several improvements have been merged into djangorestframework-stubs since the last release on December 12, I would appreciate a new release. :)

**Comment by sobolevn** [comment]
@mkurnikov please 🙂

**Comment by hannseman** [comment]
Any blockers for creating a new release?

**Comment by sobolevn** [comment]
Nope, will do today. Sorry for the delay.

**Comment by MikeFreyberger** [comment]
Any update here?

**Comment by mkurnikov** [comment]
I've published 1.2.0 with changes from the latest master. 
https://pypi.org/project/djangorestframework-stubs/1.2.0/

**Comment by sobolevn** [comment]
@mkurnikov thanks a lot! I have been to busy this week, sorry!

🙏
