### ISSUE TITLE
[New Release]

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [typeddjango/djangorestframework-stubs#707]
Hey Hey,

Can we have a new release fairly soon ?
This package is holding us back: `djangorestframework-stubs[compatible-mypy] 3.15.1 depends on mypy~=1.11.0; extra == "compatible-mypy"` and the dependency has already been updated in `setup.py`

Thanks a lot

**Comment by alexdloia** [comment]
I'm having the same issue - this would be much appreciated, thanks!

**Comment by intgr** [comment]
It's done. Thanks @alexdloia for the PR

* https://github.com/typeddjango/djangorestframework-stubs/releases/tag/3.15.2
* https://pypi.org/project/djangorestframework-stubs/#history
