### ISSUE TITLE
Refine `to_internal_value` and `to_representation` for fields

### ISSUE THREAD

**Issue by rik** [typeddjango/djangorestframework-stubs#72]
Right now, the stubs always return `Any`. I'd like to add specialised annotations for subclasses of Field. Before spending time on it, I'd like to know if that would be accepted.

https://github.com/typeddjango/djangorestframework-stubs/blob/673dc70790c671838db7b624a78a62cf4a7b7bd2/rest_framework-stubs/fields.pyi#L100-L101

**Comment by rik** [comment]
I just noticed the labels (Github didn't send me an email). Do they mean you're interested in a PR?

**Comment by sobolevn** [comment]
Yes, we totally are!

**Comment by Goldziher** [comment]
Done @sobolevn :)
