### ISSUE TITLE
Support python3.8

### ISSUE THREAD

**Issue by sobolevn** [typeddjango/djangorestframework-stubs#77]

**Comment by morrme** [comment]
@sobolevn Can you add information about what may be needed to help with this?

**Comment by sobolevn** [comment]
We can start with adding `3.8` to CI, then fix any issues that might be found.

**Comment by morrme** [comment]
I'd like to help 🙂

**Comment by sobolevn** [comment]
Thank you!

**Comment by morrme** [comment]
@sobolevn  Did you see my questions on gitter?

**Comment by sobolevn** [comment]
@morrme nope, sorry. Can you please cross-post them here?
