### ISSUE TITLE
Request incorrectly disallows ForcedAuthentication

### ISSUE THREAD

**Issue by tkadur** [typeddjango/djangorestframework-stubs#80]
Fields like `Request.successful_authenticator` can be a `ForcedAuthentication` - there's [code in DRF](https://github.com/encode/django-rest-framework/blob/4b06e0a5a114b7631bd237e29e2d6d22412a50bd/rest_framework/request.py#L180) that does this . The type stubs only allow `BaseAuthentication`s, but`ForcedAuthentication` doesn't derive from `BaseAuthentication`. I'd be happy to submit a PR for this.

**Comment by sobolevn** [comment]
@tkadur thanks a lot!
